spring:
  jpa:
    hibernate.ddl-auto: update
    #database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    #url: jdbc:mysql://localhost:3306/cricket?autoReconnect=true
    url: jdbc:h2:mem:cricketdb
    username: sa
    password: password
    driverClassName: org.h2.Driver

  # h2 instance
  h2:
    console:
      enabled: true

graphql:
  spqr:
    gui:
      enabled: true